/* Revised, original teaching scripts. Everyday scenarios are imagined examples,
   not claims about real people. Preserve original audio text for mismatch checks. */
(function(root){
 const C=root.MISO_CHAPTERS;
 const revisions={
 line:{title:'Move the yarn 3 spaces to the right.',say:'The yarn starts at 0. That is the middle mark. Move it 3 spaces to the right, one space at a time. The number under the yarn tells you where it is.',more:'Start at 0. Press “One right” once: you reach 1. Press again: you reach 2. Once more: you reach 3. A line with numbers placed in order is called a number line.',success:'You moved 0 → 1 → 2 → 3. The yarn is now 3 spaces to the right of where it started. The number 3 records that position.',task:'Press “One right” 3 times, or drag the yarn to 3.'},
 negative:{title:'The minus sign tells us: go left.',say:'Keep the same starting mark, 0. This time the yarn belongs 2 spaces to the left. We write that position as −2. The minus sign means the left side of 0 here.',more:'From 0, move left once to −1. Move left again to −2. The 2 tells you the distance from 0. The minus sign tells you which side.',success:'−2 and 2 are both 2 spaces from 0. −2 is on the left. 2 is on the right.'},
 map:{title:'Find a toy on a room plan.',say:'Imagine looking down at a room from above. The toy is 3 squares to the right of the centre, then 2 squares towards the top of the screen. We need both numbers to find it.',more:'The lines cross at our starting point. First press Right 3 times. Then press Up 2 times. “Up” means towards the top of this map, not lifting the toy into the air.',success:'The toy’s address needs 2 pieces: 3 across and 2 up. One number alone would not tell us both.'},
 complex:{title:'Write those 2 directions in one expression.',say:'You just used 3 across and 2 up. We can write that as 3 + 2i. Say i as “eye”. For this map, the i marks the up-and-down part, so we do not mix it with the across part.',more:'3 is the real part: the across coordinate. 2 is the imaginary part: the up coordinate. 2i means 2 * i. The word “imaginary” is a mathematical name, not a claim that the toy is fake.',success:'3 + 2i means the point 3 across and 2 up. This number has 2 parts. Its full name is a complex number.'},
 z:{title:'z is a name for the whole number.',say:'Writing 3 + 2i repeatedly is a bit long. Give the whole number a short name: z, pronounced “zed”. In z = 3 + 2i, the equals sign means both sides name the same value.',more:'Imagine labelling a box “z”. Inside that box is the whole expression 3 + 2i. The label does not mean just the 3, or just the 2i.'},
 square:{title:'How much fabric covers this square rug?',say:'Imagine making a rug from little fabric squares. It is 3 squares wide and 3 squares tall. Fill the rug to find how many pieces you need. The calculation is 3 * 3.',more:'There are 3 pieces in each row. There are 3 rows: 3 + 3 + 3 = 9. We write repeated equal groups as 3 * 3 = 9. Because both numbers are the same, we also write 3², pronounced “3 squared”.',success:'3 * 3 = 9 pieces cover the rug. This is its area: the amount of surface covered. 3² means 3 * 3, not 3 * 2.',tokens:[['3 * 3','3 rows, 3 pieces in each'],['*','asterisk · means multiply here'],['3²','3 squared · 3 * 3']]},
 root:{title:'You have 9 pieces. How wide can the rug be?',kind:'rug',say:'Now imagine you have exactly 9 fabric squares. You want a square rug with no pieces left over. Drag to change its side length. Which size uses all 9 pieces?',more:'A side of 2 uses 2 * 2 = 4 pieces: too few. A side of 4 uses 4 * 4 = 16: too many. A side of 3 uses 3 * 3 = 9. Finding the side from the area is called taking a square root.',success:'√9 = 3. Read it as “the square root of 9 equals 3”. You used the area, 9, to find the side length, 3. That is useful when you know how much fabric you have but not how wide to make the rug.',task:'Resize the rug until it uses exactly 9 pieces. Then check.',tokens:[['√','square-root sign'],['√9 = 3','area 9 → side 3'],['*','multiply · side * side']]},
 'negative-square':{title:'Can a square calculation give −1?',say:'We are now working with numbers, not rug sizes. Try changing the number below. 1 * 1 = 1. Also, (−1) * (−1) = 1. No real number multiplied by itself gives −1.',more:'Multiplying by −1 reverses a direction. Start at 1: reverse once to −1, then reverse again to 1. That is why (−1) * (−1) = 1. Positive * positive is also positive, and 0 * 0 = 0.',task:'Try the number slider. Then choose (−1) * (−1).',question:'What is (−1) * (−1)?'},
 'define-i':{title:'A new number for a question we could not answer.',say:'The question is: what number multiplied by itself gives −1? The real numbers cannot do that. We introduce a new number, i, with the rule i * i = −1. This lets us answer more equations.',more:'i is called the imaginary unit. It has a fixed rule, like a new tool with instructions. i² means i * i. It is not a mystery letter whose value you need to guess.',tokens:[['i','eye · imaginary unit'],['i²','i squared · i * i'],['−1','negative 1']],options:['i * i = −1','i * i = 1','i = 0']},
 quarter:{title:'Turn an arrow from right to up.',say:'Imagine turning a direction arrow on a game map. Start with it pointing right. Multiplying by i turns it a quarter-turn anticlockwise: from right to up. Try the turn and watch its tip move.',more:'Anticlockwise means the opposite direction to a clock’s hands. A quarter of a full turn is 90 degrees, written 90°. This is rotation around 0, not adding an upward step.'},
 twice:{title:'Do the same turn twice.',say:'Start on the right at 1. After 1 quarter-turn you reach i, at the top. After 2 quarter-turns you reach −1, on the left. That is 1 * i * i = −1, drawn as a movement.',more:'1 quarter-turn + 1 quarter-turn = half a turn. You are facing the opposite way. The rule i * i = −1 and this picture describe the same calculation.'},
 cycle:{title:'Follow the arrow all the way around.',say:'Turn 4 times. Watch the positions: 1 → i → −1 → −i → 1. You finish where you started. This repeating pattern saves us from writing out lots of multiplications.',more:'i⁴ means i * i * i * i. Four quarter-turns make one full turn, so i⁴ = 1. One more multiplication starts again: i⁵ = i.'},
 addition:{title:'Combine 2 sets of directions.',say:'Imagine a toy robot is already 2 squares right and 1 up. Give it a new instruction: move another 2 right and 2 up. Where will it finish? That is what adding these 2 complex numbers finds.',more:'Count sideways separately: 2 + 2 = 4. Count upward separately: 1 + 2 = 3. The answer is 4 + 3i. Do not add across and up into one direction.'},
 subtract:{title:'Undo a set of directions.',say:'Your robot starts at 3 + i: 3 right and 1 up. Subtracting 2 − 2i means undoing “2 right and 2 down”. So move 2 left and 2 up.',more:'Across: 3 − 2 = 1. Up: 1 − (−2) = 3. Undoing a downward move adds an upward move. The minus sign before the brackets reverses both parts.'},
 parts:{title:'Keep across and up separate.',say:'Combine 4 + 3i and 3 − 2i. Across: 4 + 3 = 7. Up: 3 − 2 = 1. Put those results back together: 7 + i. We usually leave out the 1 in 1i.',more:'Imagine directions on a room plan. Adding the across numbers tells you the sideways position. Adding the up numbers tells you the other position. Keep these separate so the final address is not lost.'},
 multiply:{title:'Multiply 2 groups, one pair at a time.',say:'The brackets in (1 + i) * (1 + i) hold each group together. Every part in the first group must multiply every part in the second. Start with 1 * 1. The highlighted box shows the pair to do now.',more:'The 4 pairs are 1 * 1 = 1; 1 * i = i; i * 1 = i; and i * i = −1. Add their results: 1 + i + i − 1. The 1 and −1 cancel, leaving 2i.'},
 'book-product':{title:'Use the same 4 boxes with bigger numbers.',say:'Now use the book’s example: (3 + 5i) * (4 − 3i). It still needs only 4 pair calculations. Work on the highlighted pair. You do not need to hold all 4 in your head.',more:'3 * 4 = 12. 3 * (−3i) = −9i. 5i * 4 = 20i. Finally, 5i * (−3i) = −15i² = 15. Add the real parts, then the i parts: 27 + 11i.'},
 mirror:{title:'Reflect the point below the line.',say:'The point is 3 right and 2 up. Its reflection is 3 right and 2 down: 3 − 2i. We call this reflected number the conjugate. It will help us simplify division in the next 2 steps.',more:'Keep the real part, 3. Change the sign of the imaginary part: 2 becomes −2. The little bar over z, written z̄, means “the conjugate of z”.'},
 'cancel-i':{title:'Why use that reflection?',say:'Here is the useful part: multiply a number by its conjugate and the i terms cancel. For (2 − 5i) * (2 + 5i), the result is 4 + 25. That leaves an ordinary real number.',more:'Multiply the pairs: 4 + 10i − 10i − 25i². The +10i and −10i cancel. Since i² = −1, the last term becomes +25. Now add 4 + 25.'},
 divide:{title:'Make the bottom of a fraction simpler.',say:'We want to divide (3 + 4i) by (2 − 5i). Multiply the bottom by its conjugate, 2 + 5i, to remove its i terms. We must multiply the top by the same number so the fraction keeps its value.',more:'Think of 1/2 = 2/4: both top and bottom were multiplied by 2. Here the same idea gives top −14 + 23i and bottom 29. The answer is (−14 + 23i) / 29. Never divide by 0.'},
 distance:{title:'How much ribbon reaches straight across?',say:'Imagine a gift display. One corner is 3 units across and 4 units up from the other. You want ribbon straight between them, not around the edges. How long should the ribbon be?',more:'The across and up edges meet at a right angle. Pythagoras gives: ribbon² = 3² + 4² = 9 + 16 = 25. Take the square root: ribbon = √25 = 5. Going around the edges would use 3 + 4 = 7.',task:'Compare the straight route with the edges. Set the ribbon length, then check.'},
 modulus:{title:'A short symbol for that straight distance.',say:'The straight distance you just found was 5. For a complex number, that distance from 0 has a name: modulus. The bars in |3 + 4i| ask for that distance, so |3 + 4i| = 5.',more:'Read |z| as “the modulus of z”. The 2 vertical bars mean distance here, not brackets or division. A distance cannot be negative. At 0, the distance is 0.'},
 surd:{title:'Keep an exact length without rounding.',say:'Imagine a square with area 12. Its side is √12. That is not a whole number. We can write the exact same length more simply: √12 = √(4 * 3) = 2√3.',more:'Why does 2√3 work? Square it: (2 * √3) * (2 * √3) = 4 * 3 = 12. An irrational root such as √3 is called a surd. This splitting rule is for non-negative real numbers.'},
 'roots-equation':{title:'Which 2 numbers give this square?',say:'An equation is a question with a missing value. z² + 25 = 0 asks which z makes the result 0. Subtract 25 from both sides: z² = −25. Both 5i and −5i work.',more:'Check each answer: (5i) * (5i) = 25i² = −25. Also, (−5i) * (−5i) = 25i² = −25. The sign ± means “plus or minus”: write down both answers.'},
 'complete-square':{title:'Find the number before adding 1.',say:'We need (z + 1)² = −1. We already know the numbers that square to −1: i and −i. So z + 1 must be i or −i. Subtract 1 to find z.',more:'From z + 1 = i, subtract 1 to get z = −1 + i. From z + 1 = −i, get z = −1 − i. This also solves z² + 2z + 2 = 0, because (z + 1)² = z² + 2z + 1.'},
 polar:{title:'Give a direction, then a distance.',say:'Imagine aiming a torch along a floor plan. Another way to locate a point is to give the direction and distance from the start. Point straight up, 90°, and travel 2 units. That reaches 2i.',more:'r means radius: the distance from 0. θ is the Greek letter theta: the turn angle, measured from the right. Together they describe polar form. At 0 there is no direction, so its angle is undefined.'},
 trig:{title:'How much across? How much up?',say:'Turn the 2-unit pointer. The orange line shows how far across its tip is. The purple line shows how far up it is. Cosine and sine are the rules that turn the angle into those 2 coordinates.',more:'For radius r and angle θ: across = r * cos θ, and up = r * sin θ. Say cos as “cosine” and sin as “sine”. At r = 2 and θ = 60°, across = 1 and up = √3.',task:'Turn to 60°. Watch the orange across line and purple up line.'},
 'polar-book':{title:'Put across and up back together.',say:'We already have across = r * cos θ and up = r * sin θ. A complex number is across + i * up. Putting these together gives r * (cos θ + i * sin θ).',more:'For r = 2 and θ = 120°, the tip is left of 0 and above it. Across = −1; up = √3. So the complex number is −1 + √3i. “cis θ” is a shorthand for cos θ + i * sin θ.'},
 radians:{title:'2 names for the same half-turn.',say:'Degrees and radians both measure turns, just as metres and centimetres both measure length. A half-turn is 180°, or π radians. Say π as “pi”, like “pie”. The turn itself has not changed.',more:'A full turn is 360° = 2π radians. A quarter-turn is 90° = π/2 radians. One radian covers an arc as long as the radius. Check your angle unit before calculating.'},
 'polar-product':{title:'Combine a turn and a stretch.',say:'Imagine a game arrow with length 2 pointing at 30°. Apply a stretch by 3 and a turn of 60°. Its new length is 2 * 3 = 6. Its new angle is 30° + 60° = 90°.',more:'Complex multiplication combines these changes: multiply lengths, add angles. Length 6 pointing straight up is 6i. Multiplying by i is the special case: stretch by 1 and turn 90°.'},
 'polar-divide':{title:'Undo that turn and stretch.',say:'The arrow now has length 6 and angle 90°. Undo a stretch by 3: 6 / 3 = 2. Undo a turn of 60°: 90° − 60° = 30°. This is division in polar form.',more:'Divide lengths and subtract angles. The result returns to length 2 at 30°. You cannot undo multiplication by 0 by dividing: division by 0 is undefined.'},
 powers:{title:'Repeat one instruction 3 times.',say:'Start at 1. Each button press stretches the arrow by 2 and turns it 30°. After 3 presses, the length is 2 * 2 * 2 = 8, and the angle is 30° + 30° + 30° = 90°.',more:'z³ means z * z * z. In polar form, raise the radius to the power and multiply the angle by that power. For integer powers this rule is called De Moivre’s theorem.'},
 'four-roots':{title:'Which numbers become 1 after 4 factors?',say:'A square root undoes squaring. A fourth root undoes raising to the fourth power. Here we want z * z * z * z = 1. The 4 answers are marked around the circle.',more:'Test i: i² = −1, then i⁴ = (−1) * (−1) = 1. The other answers are 1, −1 and −i. Their angles are 0°, 90°, 180° and 270°. Multiplying any of those angles by 4 ends on a full turn.'},
 'cube-roots':{title:'Find every starting point that cubes to 8i.',say:'We want z * z * z = 8i. The result has length 8, so each root has length 2: 2 * 2 * 2 = 8. Its angle is 90°. Divide possible turn totals by 3 to find the starting angles.',more:'90° / 3 = 30°. Add a full turn first: (90° + 360°) / 3 = 150°. Add 2 full turns: (90° + 720°) / 3 = 270°. Those are 3 different starts with the same cubed result.'},
 identity:{title:'One result, calculated in 2 ways.',say:'Square cos θ + i * sin θ. The turn rule doubles the angle, so the real part is cos(2θ). Multiplying the brackets gives real part cos²θ − sin²θ. These must match: they describe the same result.',more:'The pairs are cos²θ, i * cos θ * sin θ, i * sin θ * cos θ, and −sin²θ. The real parts combine to cos²θ − sin²θ. Notice: cos²θ means square the cosine; cos(2θ) means take the cosine of twice the angle.'},
 triple:{title:'Use the same idea for a triple angle.',say:'Cubing cos θ + i * sin θ triples the angle. Its imaginary part is sin(3θ). Expanding the 3 factors gives that same part as 3 * cos²θ * sin θ − sin³θ.',more:'Use cos²θ = 1 − sin²θ. Then 3 * (1 − sin²θ) * sin θ − sin³θ becomes 3 * sin θ − 3 * sin³θ − sin³θ. Combine the last 2 terms: 3 * sin θ − 4 * sin³θ.'}
 };
 for(const c of C)for(const s of c.steps){
  s.originalNarration={say:s.say,more:s.more,success:s.success};
  Object.assign(s,revisions[s.id]||{});
  for(const k of ['say','more','success','question','task'])if(s[k])s[k]=s[k].replaceAll('×','*');
  s.tokens=s.tokens.map(([a,b])=>[a.replaceAll('×','*'),b]);
  if(s.options)s.options=s.options.map(x=>x.replaceAll('×','*'));
 }
 C[0].name='Give the yarn an address';C[1].name='Squares, roots, and a new number';
 if(typeof module!=='undefined')module.exports=C;
})(typeof window!=='undefined'?window:globalThis);
